### ISSUE TITLE
Feature | Mailing List

### ISSUE THREAD

**Issue by ThomasLatham** [ThomasLatham/tlb-app#11]
# Description

Enable users to subscribe to email notifications for new posts and website updates.

# Motivation

From a user perspective, makes it easier and more convenient for users to consume the blog's content.

From a blog-growth perspective, it would drive traffic.

From a development/educational perspective, it's a good way to learn the technologies involved in mailing lists. I think it would probably also involve actually using HTTP requests in the app, so that would be cool.

# Requirements

- users should be able to subscribe selectively:
  - subscribe by post tag
  - just new posts or also post updates
  - website updates
- users should be able to update their subscription preferences
  - this will be done (for now) by just sending the form again
- users should have to solve a captcha in order to subscribe/update subscription preferences

# Sub-tasks

## Infrastructure
- [x] figure out service to be used for managing mailing list -> Mailjet
- [x] set up email hosting through Google Workspace using your Vercel domain (tomlatham.blog)
  - this requires creating DNS records for the Vercel domain so that Google can validate it
  - we want to use this domain (rather than gmail) to avoid going into people's spam folder
- [x] verify your Vercel domain in Mailjet 
  - use [SPF & DKIM Authentication](https://documentation.mailjet.com/hc/en-us/articles/360042412734-Authenticating-Domains-with-SPF-DKIM) by creating DNS records in Vercel)
- [x] verify your email address (from Google Workspace but using Vercel domain) with Mailjet
  - now you can send emails using this address programmatically via Mailjet's APIs
- [x] modify Mailjet contact properties so that you can tailor correspondence-sending to their interests
- [ ] create 2 email templates: one for new-post notifications and one for website-update notifications
- [x] set up an automation script that will:
  - see when you push a new post to `main`
  - read that post's tags
  -  send out notification emails to users who are subscribed to those tags
- will send out website-update notifications manually, since those sort of changes don't lend themselves super well to automation

## Website Development
- [x] refactor the `src/content/posts` directory and retrieval code such that each post gets its own directory
  - doing this because we want to be able to put images/resources next to the posts to which they belong, and we're soon going to set up some automation around new posts and sending emails, so want to have the file structure squared away
- [x] create the page and form for users to subscribe to the mailing list
- [x] write the server-side code for sending the subscription request
  - use [API routes](https://nextjs.org/docs/pages/building-your-application/routing/api-routes)
- [x] update the contact email address listed in the about page and in any posts

**Comment by ThomasLatham** [comment]
Finished by #29 with a bugfix from #30.
